db.url=jdbc:postgresql://localhost:5435/cmygehm_db
db.username=postgres
db.password=postgres
db.schema=homework_4

db.pool.maximumPoolSize=10
db.pool.minimumIdle=2
db.pool.poolName=SpringHikariPool
db.pool.autoCommit=true
